### PR TITLE
Fix workflowoverview for big instances

### LINKED ISSUE #170: Bug: workflowoverview page causes memory overflow on big instances
On big instances it is not possible anymore to configure any workflows, because trying to create a new one or editing an existing one will exceed the memory the request can take. This is likely to be caused by the fact that the check function of *every* configured trigger will be called *for every single course* just to show the number of courses which will be triggered in the workflowoverview page (see `get_count_of_courses_to_trigger_for_workflow` function).

I admit, it's a nice feature, but on instances with a lot of courses (for example ~400 000), this will exceed the memory stack and make the whole plugin unusable, because you cannot configure any workflow anymore. I believe this can also be an issue if triggers with pretty complex `check_course` functions are being used (including expensive SQL statements on big tables), so probably this not only can cause memory exhaustion, but can also lead to timeouts if the request takes too long to perform.

### PR DESCRIPTION
**Pull request by PhMemmel**
Closes #170 

I decided to make this feature an admin setting. So if an admin experiences performance issues he can deactive the config setting and still will have the opportunity to configure workflows.

This also can be seen as workaround for #169, not a real fix for this issue though :-)

### CODE REVIEW

**Comment by NinaHerrmann** [comment]
I thought I update the pipeline I hope this was okay :)

File: workflowoverview.php [hunk 1]
```diff
@@ -176,10 +185,11 @@
...
     'trigger' => array_values($triggers),
-    'automatic' => $displaytotaltriggered,
-    'coursestriggered' => $amounts['all']->triggered,
-    'coursesexcluded' => $amounts['all']->excluded,
-    'coursesetsize' => $amounts['all']->coursesetsize,
+    'showcoursecounts' => $showcoursecounts,
+    'automatic' => $showcoursecounts ?? $displaytotaltriggered,
+    'coursestriggered' => $showcoursecounts ?? $amounts['all']->triggered,
+    'coursesexcluded' => $showcoursecounts ?? $amounts['all']->excluded,
+    'coursesetsize' => $showcoursecounts ?? $amounts['all']->coursesetsize,
```
Comment (justusdieckmann) [inline workflowoverview.php:192]: `$a ?? $b` returns `$a` only if `isset($a) && $a !== null` and `$b` otherwise. So even if showcoursecounts is enabled, 'automatic' and the 'course*' fields will always just be set to `'1'`.

Depending on your preferences, you can use for example `... => $amounts['all']->triggered ?? null` (since ?? luckily tests for `isset`, there will be no warnings that way), or `... => $showcoursecounts ? $amounts['all']->triggered : null`, or just move those values out of the initial array creation and set them seperately only `if ($showcoursecounts) {...}`.

Comment (PhMemmel) [reply workflowoverview.php:192]: Oh wow, that was definitely a brain fart, sorry for that and thank you for spotting :+1:

I of course tested only one course in a workflow and - guess what - it "worked" :see_no_evil: :smile:

**Comment by PhMemmel** [comment]
Requested changes done, I also rebased onto current master. Thank you for the review!

File: workflowoverview.php (hunk 1 above)
Comment (justusdieckmann) [reply workflowoverview.php]: No worries, thats what reviews are for :D

**Review by justusdieckmann — APPROVED** [review]
Thank you very much!
